spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    testdb:
      jdbcUrl: jdbc:postgresql://localhost:5432/testdb
      username: postgres
      password: 123456
      driverClassName: org.postgresql.Driver
    testdb2:
      jdbcUrl: jdbc:postgresql://localhost:5432/testdb2
      username: postgres
      password: 123456
      driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres